import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles(() => ({
  postTitle: {
    margin: '15px',
    marginBottom: '15px',
    fontFamily: 'Alegreya Sans SC',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '35px',
    lineHeight: '40px',
    color: '#000000',
  },
  post: {
    border: '1px solid #000000',
  },
  postName: {
    margin: '15px',
    marginBottom: '15px',
    fontFamily: 'Alegreya Sans SC',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '35px',
    lineHeight: '40px',
    color: '#000000',
  },
  postBody: {
    margin: '15px',
    marginBottom: '15px',
    fontFamily: 'Open Sans',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '15px',
    lineHeight: '21px',
    color: 'rgba(0, 0, 0, 0.80)',
  },
  commTitle: {
    margin: '30px',
    marginBottom: '15px',
    fontFamily: 'Alegreya Sans SC',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '35px',
    lineHeight: '40px',
    color: '#000000',
  },
  commList: {
    margin: '30px',
    display: 'grid',
    gridTemplateRows: '1fr 1fr 1fr',
    gridGap:' 2vw',
  },
  commHead: {
    border: '1px solid #000000',
  },
  commName: {
    margin: '10px',
    fontFamily: 'Open Sans',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '17px',
    lineHeight: '23px',
    textTransform: 'capitalize',
    color: '#000000',
  },
  commEmail: {
    margin: '10px',
    fontFamily: 'Open Sans',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '12px',
    lineHeight: '23px',
    textTransform: 'capitalize',
    color: '#000000',
  },
  commText: {
    margin: '10px',
    fontFamily: 'Open Sans',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '17px',
    lineHeight: '18px',
    color: 'rgba(0, 0, 0)',
  },
}));

export default useStyles;
