//customid 0-imperium, 1-chaos, 2-tau, 3-necrons, 4-tyranids, 5-orks, 6-eldar, 7-darkeldars
exports.product = [
  {
    "spacemarine": {
      shopCartId: 0,
      img: "spacemarine.jpg",
      description: "",
      price: "500",
      name:"space marine",
      race: "imperium",
      type: "infantry",
    },
    "imperialguard": {
      shopCartId: 1,
      img: "imperialguard.jpg",
      description: "",
      price: "1000",
      name:"imperial guard",
      race: "imperium",
      type: "infantry",
    },
    "chaosspacemarine": {
      shopCartId: 2,
      img: "chaosspacemarine.jpg",
      description: "",
      price: "700",
      name:"chaos space marine",
      race: "chaos",
      type: "infantry",
    },
    "imperialtank": {
      shopCartId: 3,
      img: "imperialtank.jpg",
      description: "",
      price: "400",
      name:"imperial tank",
      race: "imperium",
      type: "vechical",
    },
    "chaostank": {
      shopCartId: 4,
      img: "chaostank.jpg",
      description: "",
      price: "900",
      name:"chaos tank",
      race: "chaos",
      type: "vechical",
    },
    "ultramarin": {
      shopCartId: 5,
      img: "imperialtank.jpg",
      customRace: "imperium",
      customId: 0,
      name:"ultramarin",
      price: "",
      description: "",
    },
    "demon" : {
      shopCartId: 6,
      img: "imperialtank.jpg",
      customRace: "chaos",
      customId: 1,
      name:"demon",
      price: "",
      description: "",
    },
    "robouteguilliman" : {
      shopCartId: 7,
      img: "imperialtank.jpg",
      customRace: "imperium",
      customId: 0,
      name:"roboute guilliman",
      price: "",
      description: "",
    },
    "valkyrie": {
      shopCartId: 8,
      img: "imperialtank.jpg",
      customRace: "imperium",
      customId: 0,
      name:"valkyrie",
      price: "",
      description: "",
    }
  }
]
