import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles(() => ({
  infoCustomers: {
    width: '374px',
    height: '100vh',
    background: '#FFFFFF',
    borderRadius: '10px',
  },
  container: {
    boxSizing: 'border-box',
    padding: '62px 12% 12% 12%',
    textAlign: 'center',
    height: '100%',
  },
  name: {
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '22px',
    lineHeight: '30px',
    textTransform: 'Capitalize',
    color: '#030229',
  },
  profession: {
    marginTop: '8px',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '19px',
    textTransform: 'Capitalize',
    color: '#030229',
  },
  body: {
    textAlign: 'start',
    marginTop: '70px',
  },
  cross: {
    float: 'right',
    verticalAlign: 'middle',
    cursor: 'pointer',
    marginTop: '5%',
    marginRight: '5%',
  },
  string: {
    float: 'none',
    position: 'relative',
    boxSizing: 'border-box',
    margin: '20px 0 20px 0',
    '&:before': {
      content: '',
      position: 'absolute',
      left: 1,
      top: 100,
      width: '20px',
      height: '2px',
    },
  },
  svg: {
    display: 'inline-block',
    verticalAlign: 'middle',
    marginRight: '5%',
    opacity: 0.7,
  },
  p: {
    width: '200px',
    display: 'inline-block',
    verticalAlign: 'top',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '22px',
    color: '#030229',
    opacity: 0.7,
  },
  charts: {
    marginTop: '5%',
    height: '236px',
    padding: '20px',
    boxSizing: 'border-box',
    border: '1px solid #F7F7F8',
    borderRadius: '7px',
  },
  title: {
    width: '100%',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '18px',
    lineHeight: '25px',
    color: '#030229',
    verticalAlign: 'middle',
  },
  salesAnalyticsDots: {
    float: 'right',
    verticalAlign: 'middle',
    lineHeight: '25px',
  },
  leftCircle: {
    marginTop: '5%',
    width: '134px',
    height: '134px',
    float: 'left',
    verticalAlign: 'middle',
    boxSizing: 'border-box',
    border: '1px solid #F7F7F8',
    borderRadius: '7px',
  },
  rightCircle: {
    marginTop: '5%',
    width: '134px',
    height: '134px',
    float: 'right',
    verticalAlign: 'middle',
    boxSizing: 'border-box',
    border: '1px solid #F7F7F8',
    borderRadius: '7px',
  },
}));

export default useStyles;
