import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles(() => ({
  topContainer: {
    width: '100%',
  },
  backImg: {
    position: 'absolute',
    zIndex: -1,
    top: 0,
    left: 0,
    width: '100%',
    height: '509px',
    boxShadow: 'inset 100em 1em #5F5F5F',
  },
  centralBlock: {
    margin: '0 auto',
    marginBottom: '30px',
    width: '1000px',
    height: '156px',
    zIndex: 2,
    background: 'radial-gradient(50% 50% at 50% 50%, #000000 0%, rgba(0, 0, 0, 0) 100%)',
  },
  topTitle: {
    margin: 0,
    marginTop: '227px',
    fontFamily: 'Alegreya Sans SC',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '50px',
    lineHeight: '60px',
    textAlign: 'center',
    color: '#FFFFFF',
  },
  date: {
    margin: 0,
    fontFamily: 'Alegreya Sans SC',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '30px',
    lineHeight: '36px',
    textAlign: 'center',
    color: '#FFFFFF',
  },
  topBtns: {
    marginBottom: '76px',
    width: '100%',
    height: '40px',
  },
  centralBtn: {
    position: 'relative',
    left: '45%',
    transform: 'translate(-50%, 0)',
    padding: '11.5px 59.5px',
    border: 'none',
    cursor: 'pointer',
    fontFamily: 'Proxima Nova',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '14px',
    lineHeight: '17px',
    color: '#000000',
  },
  leftBtnArrow: {
    cursor: 'pointer',
    position: 'relative',
    width: '40px',
    height: '40px',
    marginLeft: '61px',
    float: 'left',
    boxSizing: 'border-box',
    border: '1px solid #FFFFFF',
    '&:hover': {
      background: '#FFFFFF',
      '&::after': {
        content: '""',
        position: 'absolute',
        top: 20,
        left: 16,
        width: '6px',
        height: '1px',
        borderRafdius: '100px',
        background: '#000000',
        transform: 'rotate(-130deg)',
      },
      '&::before': {
        content: '""',
        position: 'absolute',
        top: 16,
        left: 16,
        width: '6px',
        height: '1px',
        borderRafdius: '100px',
        background: '#000000',
        transform: 'rotate(130deg)',
      },
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      top: 20,
      left: 16,
      width: '6px',
      height: '1px',
      background: '#FFFFFF',
      transform: 'rotate(-130deg)',
    },
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 16,
      left: 16,
      width: '6px',
      height: '1px',
      background: '#FFFFFF',
      transform: 'rotate(130deg)',
    },
  },
  rightBtnArrow: {
    cursor: 'pointer',
    position: 'relative',
    width: '40px',
    height: '40px',
    marginRight: '61px',
    float: 'right',
    boxSizing: 'border-box',
    border: '1px solid #FFFFFF',
    '&:hover': {
      background: '#FFFFFF',
      '&::after': {
        content: '""',
        position: 'absolute',
        top: 20,
        left: 16,
        width: '6px',
        height: '1px',
        borderRafdius: '100px',
        background: '#000000',
        transform: 'rotate(-50deg)',
      },
      '&::before': {
        content: '""',
        position: 'absolute',
        top: 16,
        left: 16,
        width: '6px',
        height: '1px',
        borderRafdius: '100px',
        background: '#000000',
        transform: 'rotate(50deg)',
      },
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      top: 20,
      left: 16,
      width: '6px',
      height: '1px',
      borderRafdius: '100px',
      background: '#FFFFFF',
      transform: 'rotate(-50deg)',
    },
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 16,
      left: 16,
      width: '6px',
      height: '1px',
      borderRafdius: '100px',
      background: '#FFFFFF',
      transform: 'rotate(50deg)',
    },
  },
  bottomContainer: {
    margin: '31px 61px',
  },
  usersBlock: {

  },
  head: {
    width: '100%',
    height: '40px',
    marginBottom: '16px',
  },
  title: {
    margin: 0,
    float: 'left',
    fontFamily: 'Alegreya Sans SC',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '35px',
    lineHeight: '40px',
    color: '#000000',
  },
  count: {
    margin: 0,
    float: 'right',
    fontFamily: 'Alegreya Sans SC',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '35px',
    lineHeight: '40px',
    color: '#00000',
  },
  counter: {
    color: 'rgba(0,0,0,0.41)',
  },
  infoBlock: {
    marginTop: '47px',
    marginBottom: '57px',
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gridTemplateRows: 'repeat(1, 1fr)',
  },
  leftBlock: {
    height: '232px',
    gridColumn: 'span 3',
  },
  leftBlockTitle: {
    margin: 0,
    marginBottom: '16px',
    fontFamily: 'Alegreya Sans SC',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '35px',
    lineHeight: '40px',
    color: '#00000',
  },
  leftBlockContent: {
    direction: 'rtl',
    overflowY: 'scroll',
    margin: 0,
    padding: 0,
    listStyle: "none",
    height: "100%",
    '&::-webkit-scrollbar': {
      width: '10px',
    },
    '&::-webkit-scrollbar-track': {
      border: '4px solid transparent',
      backgroundColor: 'rgba(13, 30, 75, 0.2)',
      backgroundClip: 'content-box',
    },
    '&::-webkit-scrollbar-thumb': {
      backgroundColor: 'rgba(13, 30, 75, 1)',
      border: '1px solid rgba(13, 30, 75, 1)',
    }
  },
  leftBlockContentTitle: {
    direction: 'ltr',
    margin: '0px 60px 10px 40px',
    fontFamily: 'Open Sans',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '15px',
    lineHeight: '20px',
    color: '#000000',
  },
  leftBlockContentText: {
    direction: 'ltr',
    margin: '0px 60px 10px 40px',
    fontFamily: 'Open Sans',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '14px',
    lineHeight: '24px',
    color: '#939393',
  },
  rightBlock: {
    height: '272px',
    gridColumn: 'span 4',
    border: '1px solid #DADADA',
  },
  rightBlockTitle: {
    margin: '13px 25px 0px',
    fontFamily: 'Open Sans',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '18px',
    lineHeight: '40px',
    color: '#000000',
  },
  textarea: {
    width: '95%',
    height: '100px',
    margin: '25px 25px',
    padding: '10px 20px',
    boxSizing: 'border-box',
    border: '1px solid #0D1E4B',
    resize: 'none',
    fontFamily: 'Open Sans',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '11px',
    lineHeight: '15px',
    color: '#969696',
  },
  rightBlockBtn: {
    float: 'right',
    marginRight: '25px',
    padding: '10px 20px',
    fontFamily: 'Open Sans',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '11px',
    lineHeight: '15px',
    color: '#FFFFFF',
    background: '#101010',
  },
  footer: {
    width: '100%',
    height: '100%',
  },
  footerTitle: {
    width: '170px',
    minWidth: '150px',
    margin: 0,
    float:'left',
    verticalAlign: 'top',
    fontFamily: 'Alegreya Sans SC',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '35px',
    lineHeight: '40px',
    color: '#00000',
  },
  footerText: {
    marginBottom: '20px',
    width: 'calc(100% - 170px)',
    margin: 0,
    float: 'right',
    verticalAlign: 'bottom',
    fontFamily: 'Open Sans',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '16px',
    lineHeight: '24px',
    color: '#939393',
  },
}));

export default useStyles;
