import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles(() => ({
  openModalBtn: {
    float: 'right',
    width: '200px',
    height: '40px',
    border: 'none',
    cursor: 'pointer',
    fontFamily: 'Proxima Nova',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '14px',
    lineHeight: '17px',
    background: '#000000',
    color: '#FFFFFF',
  },
  input: {
    width: '95%',
    padding: '10px 20px',
    boxSizing: 'border-box',
    border: '1px solid #0D1E4B',
    resize: 'none',
    fontFamily: 'Open Sans',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '11px',
    lineHeight: '15px',
    color: '#969696',
  },
  textarea: {
    width: '95%',
    height: '90px',
    padding: '10px 20px',
    boxSizing: 'border-box',
    border: '1px solid #0D1E4B',
    resize: 'none',
    fontFamily: 'Open Sans',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '11px',
    lineHeight: '15px',
    color: '#969696',
  },
  pushComment: {
    float: 'right',
    width: '200px',
    height: '40px',
    margin: '70px 0 10px 0',
    border: 'none',
    cursor: 'pointer',
    fontFamily: 'Proxima Nova',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '14px',
    lineHeight: '17px',
    background: '#000000',
    color: '#FFFFFF',
  },
  pushAlertComment: {
    float: 'right',
    width: '100px',
    height: '40px',
    margin: '10px 0 10px 0',
    border: 'none',
    cursor: 'pointer',
    fontFamily: 'Proxima Nova',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: '11px',
    lineHeight: '15px',
    background: '#c10000',
    color: 'white',
  }
}));

export default useStyles;